# Generated by Django 5.2.10 on 2026-01-15 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(help_text='Google map link / address / coordinates', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('pan_number', models.CharField(max_length=10)),
                ('income_level', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Other', 'Other')], max_length=20)),
                ('has_kids', models.BooleanField(default=False)),
                ('referral_source', models.CharField(max_length=100)),
                ('existing_policy', models.BooleanField(default=False)),
                ('service_satisfaction', models.CharField(blank=True, max_length=200)),
                ('visited_policy', models.CharField(max_length=100)),
                ('willing_to_purchase', models.BooleanField(default=False)),
                ('willing_to_switch', models.BooleanField(default=False)),
                ('willing_to_share_previous', models.BooleanField(default=False)),
                ('previous_policy_number', models.CharField(blank=True, max_length=100)),
                ('previous_policy_name', models.CharField(blank=True, max_length=100)),
                ('previous_claimed', models.BooleanField(default=False)),
                ('customer_preferences', models.TextField(blank=True)),
                ('agent_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='app.agentprofile')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.campaign')),
            ],
        ),
    ]
