# Generated by Django 5.2.10 on 2026-01-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_agent_alter_client_agent_delete_agentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='password',
            field=models.CharField(default=True, max_length=128),
        ),
    ]
