# Generated by Django 5.2.10 on 2026-01-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_agent_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='description',
        ),
        migrations.AlterField(
            model_name='agent',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
