# Generated by Django 5.2.10 on 2026-01-15 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_campaign_description_alter_agent_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.agent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
