# Generated by Django 5.2.10 on 2026-01-20 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_client_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.agent'),
        ),
    ]
